"""empty message

Revision ID: 058557423dd8
Revises: 
Create Date: 2025-11-14 01:11:50.364691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058557423dd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buff', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Buff ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='说明',
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='持续时间（回合）',
               existing_nullable=True)
        batch_op.alter_column('is_positive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='增益还是减益',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('icon_url',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Buff图标',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='Buff表'
    )

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='挑战ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('challenge_id_seq'::regclass)"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='发起挑战的用户',
               existing_nullable=False)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='挑战的关卡',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
        batch_op.alter_column('end_hp',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='挑战结束后剩余血量',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'failed', name='challenge_status'),
               type_=sa.String(),
               nullable=True,
               comment=None,
               existing_comment='当前状态',
               existing_server_default=sa.text("'in_progress'::challenge_status"))
        batch_op.alter_column('exp_gained',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='本次挑战获得的经验',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coins_gained',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='本次挑战获得的金币',
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('challenge_level_id_idx'))
        batch_op.drop_index(batch_op.f('challenge_user_id_idx'))
        batch_op.drop_constraint(batch_op.f('challenge_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('challenge_level_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'level', ['level_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='挑战记录表'
    )

    with op.batch_alter_table('challenge_buff_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('challenge_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='挑战ID',
               existing_nullable=False)
        batch_op.alter_column('buff_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Buff ID',
               existing_nullable=False)
        batch_op.alter_column('remaining_duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='剩余回合数',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('challenge_buff_link_buff_id_idx'))
        batch_op.drop_constraint(batch_op.f('challenge_buff_link_challenge_id_buff_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('challenge_buff_link_challenge_id_idx'))
        batch_op.drop_constraint(batch_op.f('challenge_buff_link_challenge_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('challenge_buff_link_buff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'buff', ['buff_id'], ['id'])
        batch_op.create_foreign_key(None, 'challenge', ['challenge_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='挑战-Buff关联表'
    )

    with op.batch_alter_table('challenge_prop_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('challenge_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='挑战ID',
               existing_nullable=False)
        batch_op.alter_column('prop_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='道具ID',
               existing_nullable=False)
        batch_op.alter_column('remaining_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='剩余个数',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('challenge_prop_link_challenge_id_idx'))
        batch_op.drop_constraint(batch_op.f('challenge_prop_link_challenge_id_prop_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('challenge_prop_link_prop_id_idx'))
        batch_op.drop_constraint(batch_op.f('challenge_prop_link_prop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('challenge_prop_link_challenge_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'prop', ['prop_id'], ['id'])
        batch_op.create_foreign_key(None, 'challenge', ['challenge_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='挑战-道具关联表'
    )

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关卡ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('level_id_seq'::regclass)"))
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属层数',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_table_comment(
        existing_comment='关卡表'
    )

    with op.batch_alter_table('level_question_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关卡',
               existing_nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='题目',
               existing_nullable=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在关卡中的顺序',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('level_question_link_level_id_idx'))
        batch_op.drop_constraint(batch_op.f('level_question_link_level_id_order_index_key'), type_='unique')
        batch_op.drop_index(batch_op.f('level_question_link_question_id_idx'))
        batch_op.drop_constraint(batch_op.f('level_question_link_level_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('level_question_link_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'level', ['level_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='关卡-题目关联表'
    )

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='词库ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('library_id_seq'::regclass)"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='词库名',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='简介',
               existing_nullable=True)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建者',
               existing_nullable=True)
        batch_op.alter_column('visibility',
               existing_type=postgresql.ENUM('public', 'private', name='library_visibility'),
               type_=sa.String(),
               comment=None,
               existing_comment='可见性',
               existing_nullable=True,
               existing_server_default=sa.text("'public'::library_visibility"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='词库包含的单词总数',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='词库最后更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('library_creator_id_idx'))
        batch_op.drop_constraint(batch_op.f('library_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='词库表'
    )

    with op.batch_alter_table('library_word_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='词库',
               existing_nullable=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='单词',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('library_word_link_library_id_idx'))
        batch_op.drop_constraint(batch_op.f('library_word_link_library_id_word_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('library_word_link_word_id_idx'))
        batch_op.drop_constraint(batch_op.f('library_word_link_library_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('library_word_link_word_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['id'])
        batch_op.create_foreign_key(None, 'word', ['word_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='词库-单词关联表'
    )

    with op.batch_alter_table('prop', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='道具ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('prop_id_seq'::regclass)"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='道具名',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='说明',
               existing_nullable=True)
        batch_op.alter_column('rarity',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='稀有度',
               existing_server_default=sa.text('1'))
        batch_op.alter_column('icon_url',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='道具图标',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='道具表'
    )

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='题目ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('question_id_seq'::regclass)"))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='题型',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='题目内容',
               existing_nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='参考答案',
               existing_nullable=True)
        batch_op.alter_column('explanation',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='解析',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='题目表'
    )

    with op.batch_alter_table('question_word_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='题目',
               existing_nullable=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联单词',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('question_word_link_question_id_idx'))
        batch_op.drop_constraint(batch_op.f('question_word_link_question_id_word_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('question_word_link_word_id_idx'))
        batch_op.drop_constraint(batch_op.f('question_word_link_word_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('question_word_link_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'word', ['word_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='题目-单词关联表'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户唯一标识',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='昵称',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
        batch_op.alter_column('exp',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='经验值',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coins',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='金币',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='注册时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='最近登录时间',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'banned', name='user_status'),
               type_=sa.String(),
               comment=None,
               existing_comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::user_status"))
        batch_op.alter_column('max_hp',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='用户的血量上限',
               existing_server_default=sa.text('100'))
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='用户的攻击力',
               existing_server_default=sa.text('10'))
        batch_op.alter_column('crit_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='用户的暴击率',
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='用户角色',
               existing_server_default=sa.text("'player'::character varying"))
        batch_op.alter_column('max_floor',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='最高闯关层数',
               existing_server_default=sa.text('0'))
        batch_op.drop_table_comment(
        existing_comment='用户表'
    )

    with op.batch_alter_table('user_user_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户A',
               existing_nullable=False)
        batch_op.alter_column('friend_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户B',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'deleted', name='friend_status'),
               type_=sa.String(),
               nullable=True,
               comment=None,
               existing_comment='好友状态：待确认 / 已互为好友 / 已删除',
               existing_server_default=sa.text("'pending'::friend_status"))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='最近状态更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('user_user_link_friend_id_idx'))
        batch_op.drop_constraint(batch_op.f('user_user_link_user_id_friend_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('user_user_link_user_id_idx'))
        batch_op.drop_constraint(batch_op.f('user_user_link_friend_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_user_link_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['friend_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='用户好友关系表'
    )

    with op.batch_alter_table('user_word_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户',
               existing_nullable=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='单词',
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='学习时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('correct',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否答对',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('user_word_record_user_id_idx'))
        batch_op.drop_index(batch_op.f('user_word_record_user_id_word_id_idx'))
        batch_op.drop_index(batch_op.f('user_word_record_word_id_idx'))
        batch_op.drop_constraint(batch_op.f('user_word_record_word_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_word_record_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'word', ['word_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='用户单词学习记录表'
    )

    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='单词ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('word_id_seq'::regclass)"))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='单词本体',
               existing_nullable=False)
        batch_op.alter_column('meaning',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='中文释义',
               existing_nullable=True)
        batch_op.alter_column('phonetic',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='音标',
               existing_nullable=True)
        batch_op.alter_column('part_of_speech',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='词性',
               existing_nullable=True)
        batch_op.alter_column('example',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='例句',
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='难度等级',
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='标签',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='单词表'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_table_comment(
        '单词表',
        existing_comment=None
    )
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=255),
               comment='标签',
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               comment='难度等级',
               existing_nullable=True)
        batch_op.alter_column('example',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='例句',
               existing_nullable=True)
        batch_op.alter_column('part_of_speech',
               existing_type=sa.VARCHAR(length=100),
               comment='词性',
               existing_nullable=True)
        batch_op.alter_column('phonetic',
               existing_type=sa.VARCHAR(length=255),
               comment='音标',
               existing_nullable=True)
        batch_op.alter_column('meaning',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='中文释义',
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               comment='单词本体',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='单词ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('word_id_seq'::regclass)"))

    with op.batch_alter_table('user_word_record', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户单词学习记录表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_word_record_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_word_record_word_id_fkey'), 'word', ['word_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('user_word_record_word_id_idx'), ['word_id'], unique=False)
        batch_op.create_index(batch_op.f('user_word_record_user_id_word_id_idx'), ['user_id', 'word_id'], unique=False)
        batch_op.create_index(batch_op.f('user_word_record_user_id_idx'), ['user_id'], unique=False)
        batch_op.alter_column('correct',
               existing_type=sa.BOOLEAN(),
               comment='是否答对',
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='学习时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment='单词',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='用户',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='记录ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_user_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户好友关系表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_user_link_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_user_link_friend_id_fkey'), 'user', ['friend_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('user_user_link_user_id_idx'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('user_user_link_user_id_friend_id_key'), ['user_id', 'friend_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('user_user_link_friend_id_idx'), ['friend_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='最近状态更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'accepted', 'deleted', name='friend_status'),
               nullable=False,
               comment='好友状态：待确认 / 已互为好友 / 已删除',
               existing_server_default=sa.text("'pending'::friend_status"))
        batch_op.alter_column('friend_id',
               existing_type=sa.INTEGER(),
               comment='用户B',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='用户A',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户表',
        existing_comment=None
    )
        batch_op.alter_column('max_floor',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='最高闯关层数',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='用户角色',
               existing_server_default=sa.text("'player'::character varying"))
        batch_op.alter_column('crit_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               comment='用户的暴击率',
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='用户的攻击力',
               existing_server_default=sa.text('10'))
        batch_op.alter_column('max_hp',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='用户的血量上限',
               existing_server_default=sa.text('100'))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'banned', name='user_status'),
               comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::user_status"))
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='最近登录时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='注册时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('coins',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='金币',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exp',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='经验值',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='头像',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=255),
               comment='昵称',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='用户唯一标识',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))

    with op.batch_alter_table('question_word_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '题目-单词关联表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_word_link_question_id_fkey'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('question_word_link_word_id_fkey'), 'word', ['word_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('question_word_link_word_id_idx'), ['word_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('question_word_link_question_id_word_id_key'), ['question_id', 'word_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('question_word_link_question_id_idx'), ['question_id'], unique=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment='关联单词',
               existing_nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               comment='题目',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_table_comment(
        '题目表',
        existing_comment=None
    )
        batch_op.alter_column('explanation',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='解析',
               existing_nullable=True)
        batch_op.alter_column('answer',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='参考答案',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='题目内容',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               comment='题型',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='题目ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('question_id_seq'::regclass)"))

    with op.batch_alter_table('prop', schema=None) as batch_op:
        batch_op.create_table_comment(
        '道具表',
        existing_comment=None
    )
        batch_op.alter_column('icon_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='道具图标',
               existing_nullable=True)
        batch_op.alter_column('rarity',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='稀有度',
               existing_server_default=sa.text('1'))
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='说明',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='道具名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='道具ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('prop_id_seq'::regclass)"))

    with op.batch_alter_table('library_word_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '词库-单词关联表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('library_word_link_word_id_fkey'), 'word', ['word_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('library_word_link_library_id_fkey'), 'library', ['library_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('library_word_link_word_id_idx'), ['word_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('library_word_link_library_id_word_id_key'), ['library_id', 'word_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('library_word_link_library_id_idx'), ['library_id'], unique=False)
        batch_op.alter_column('word_id',
               existing_type=sa.INTEGER(),
               comment='单词',
               existing_nullable=False)
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               comment='词库',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.create_table_comment(
        '词库表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('library_creator_id_fkey'), 'user', ['creator_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('library_creator_id_idx'), ['creator_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='词库最后更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='词库包含的单词总数',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('visibility',
               existing_type=sa.String(),
               type_=postgresql.ENUM('public', 'private', name='library_visibility'),
               comment='可见性',
               existing_nullable=True,
               existing_server_default=sa.text("'public'::library_visibility"))
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               comment='创建者',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='简介',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='词库名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='词库ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('library_id_seq'::regclass)"))

    with op.batch_alter_table('level_question_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '关卡-题目关联表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('level_question_link_question_id_fkey'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('level_question_link_level_id_fkey'), 'level', ['level_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('level_question_link_question_id_idx'), ['question_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('level_question_link_level_id_order_index_key'), ['level_id', 'order_index'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('level_question_link_level_id_idx'), ['level_id'], unique=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               comment='在关卡中的顺序',
               existing_nullable=True)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               comment='题目',
               existing_nullable=False)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               comment='关卡',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.create_table_comment(
        '关卡表',
        existing_comment=None
    )
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               comment='所属层数',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='关卡ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('level_id_seq'::regclass)"))

    with op.batch_alter_table('challenge_prop_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '挑战-道具关联表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('challenge_prop_link_challenge_id_fkey'), 'challenge', ['challenge_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('challenge_prop_link_prop_id_fkey'), 'prop', ['prop_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('challenge_prop_link_prop_id_idx'), ['prop_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('challenge_prop_link_challenge_id_prop_id_key'), ['challenge_id', 'prop_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('challenge_prop_link_challenge_id_idx'), ['challenge_id'], unique=False)
        batch_op.alter_column('remaining_count',
               existing_type=sa.INTEGER(),
               comment='剩余个数',
               existing_nullable=True)
        batch_op.alter_column('prop_id',
               existing_type=sa.INTEGER(),
               comment='道具ID',
               existing_nullable=False)
        batch_op.alter_column('challenge_id',
               existing_type=sa.INTEGER(),
               comment='挑战ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('challenge_buff_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '挑战-Buff关联表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('challenge_buff_link_buff_id_fkey'), 'buff', ['buff_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('challenge_buff_link_challenge_id_fkey'), 'challenge', ['challenge_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('challenge_buff_link_challenge_id_idx'), ['challenge_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('challenge_buff_link_challenge_id_buff_id_key'), ['challenge_id', 'buff_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('challenge_buff_link_buff_id_idx'), ['buff_id'], unique=False)
        batch_op.alter_column('remaining_duration',
               existing_type=sa.INTEGER(),
               comment='剩余回合数',
               existing_nullable=True)
        batch_op.alter_column('buff_id',
               existing_type=sa.INTEGER(),
               comment='Buff ID',
               existing_nullable=False)
        batch_op.alter_column('challenge_id',
               existing_type=sa.INTEGER(),
               comment='挑战ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.create_table_comment(
        '挑战记录表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('challenge_level_id_fkey'), 'level', ['level_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('challenge_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('challenge_user_id_idx'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('challenge_level_id_idx'), ['level_id'], unique=False)
        batch_op.alter_column('coins_gained',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='本次挑战获得的金币',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exp_gained',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='本次挑战获得的经验',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('in_progress', 'completed', 'failed', name='challenge_status'),
               nullable=False,
               comment='当前状态',
               existing_server_default=sa.text("'in_progress'::challenge_status"))
        batch_op.alter_column('end_hp',
               existing_type=sa.INTEGER(),
               comment='挑战结束后剩余血量',
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='结束时间',
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               comment='挑战的关卡',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               comment='发起挑战的用户',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='挑战ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('challenge_id_seq'::regclass)"))

    with op.batch_alter_table('buff', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Buff表',
        existing_comment=None
    )
        batch_op.alter_column('icon_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='Buff图标',
               existing_nullable=True)
        batch_op.alter_column('is_positive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='增益还是减益',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               comment='持续时间（回合）',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='说明',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='Buff ID',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
