"""题目表的content改为JSONB，去除了两个无用属性

Revision ID: 390753d1be31
Revises: dd56af527a03
Create Date: 2025-11-24 19:48:34.393359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390753d1be31'
down_revision: Union[str, Sequence[str], None] = 'dd56af527a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('explanation')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
