"""增加了用户选择词库的排序优先级

Revision ID: dd56af527a03
Revises: fe59fe405a95
Create Date: 2025-11-19 23:23:28.948136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd56af527a03'
down_revision: Union[str, Sequence[str], None] = 'fe59fe405a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library_select', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library_select', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
